//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HundredeDagesLogen {
    
    
    public partial class Index {
        
        /// <summary>
        /// SpaForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm SpaForm;
        
        /// <summary>
        /// userControlWelcome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.Welcome userControlWelcome;
        
        /// <summary>
        /// UCMembers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.Members UCMembers;
        
        /// <summary>
        /// UCMemberDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.MemberDetails UCMemberDetails;
        
        /// <summary>
        /// userControlMeetings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.Meetings userControlMeetings;
        
        /// <summary>
        /// userControlFinances control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.Finances userControlFinances;
        
        /// <summary>
        /// userControlPhotoAlbums control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.PhotoAlbums userControlPhotoAlbums;
        
        /// <summary>
        /// userControlPhotoAlbum control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.PhotoAlbum userControlPhotoAlbum;
        
        /// <summary>
        /// userControlAbout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.About userControlAbout;
        
        /// <summary>
        /// UCDialogs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::HundredeDagesLogen.UserControls.Dialogs UCDialogs;
    }
}
